[deps]
AbstractMCMC = "80f14c24-f653-4e6a-9b94-39d6b0f70001"
CategoricalArrays = "324d7699-5711-5eae-9e2f-1d82baa6b597"
ColorSchemes = "35d6a980-a343-548e-a6ea-1d62b119f2f4"
DataFramesMeta = "1313f7d8-7da2-5740-9ea0-a2ca25f37964"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
FreqTables = "da1fdf0e-e0ff-5433-a45f-9bb5ff651cb1"
HypothesisTests = "09f84164-cd44-5f33-b23f-e6b0d136a0d5"
Images = "916415d5-f1e6-5110-898d-aaa5f9f070e0"
Latexify = "23fbe1c1-3f47-55db-b15f-69d7ec21a316"
Missings = "e1d29d7a-bbdc-5cf2-9ac0-f12de2c33e28"
MultipleTesting = "f8716d33-7c4a-5097-896f-ce0ecbd3ef6b"
PlutoUI = "7f904dfe-b85e-4ff6-b463-dae2292396a8"
PrettyTables = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"
RCall = "6f49c342-dc21-5d91-9882-a32aef131414"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"
